#!/bin/bash

set -eu

version=$1 ; shift

if [ -d "_log/${version}" ] ; then
  echo "already ${version} have been released"
  exit 1
fi

sed -i -e "s!return \"[^\"]*\" // Version!return \"$version\" // Version!" proxyexam.go

git add -u
git commit -m "bump up version: $version"
git tag -m "${version}: release $(git rev-parse) as ${version}" "${version}"

git push
git push --tags

echo "release ${version}" >> _log/log.txt

mkdir -p "_log/${version}"
curl -s "https://proxy.golang.org/github.com/koron/proxyexam/@v/list" -o "_log/${version}/list.txt"
curl -s "https://proxy.golang.org/github.com/koron/proxyexam/@latest" -o "_log/${version}/latest.json"
