#!/bin/bash

set -eu

version=$1 ; shift

if [ -d "_log/${version}" ] ; then
  echo "already ${version} have been released"
  exit 1
fi

sed -i -e "s!return \"[^\"]*\" // Version!return \"$version\" // Version!" proxyexam.go

git add -u
git commit -m "bump up version: $version"
git tag -m "${version}: release $(git rev-parse) as ${version}" "${version}"

git push
git push --tags

echo "release ${version}" >> _log/log.txt
mkdir -p "_log/${version}"

echo ""
echo "${version} released"

sleep 5

curl -s "https://proxy.golang.org/github.com/koron/proxyexam/@v/${version}.info" -o "_log/${version}/info.json"
echo ""
echo "_log/${version}/info.json"
cat "_log/${version}/info.json"
echo ""

sleep 1

$(dirname "$0")/logproxy ${version}
